### ISSUE TITLE
unenv-nightly versioning is problematic

### ISSUE THREAD

**Issue by IgorMinar** [unjs/unenv#246]
### Environment

unenv-nightly

### Reproduction

pnpm info unenv-nightly versions

### Describe the bug

the unenv-nightly@latest flip flops between patch and minor version bumps

For example after https://github.com/unjs/unenv/actions/runs/9323911293/job/25668071381, the @latest was set to 1.10:
```
[info] Bumping npm package version from `1.9.0` to `1.10.0-1717187105.3931166` (minor)
```

But subsequently when another fix was released in https://github.com/unjs/unenv/actions/runs/9324677049/job/25670351927 the @latest became 1.9.x:
```
[info] Bumping npm package version from `1.9.0` to `1.9.1-1717191795.bd5ba19` (patch)
```

Ideally all releases from main target 1.10 or even 2.0 release train regardless of their semantic commit message.

Additionally, it would be great to make the timestamp in the version tag human readable. Perhaps: 202405311022.

**Comment by pi0** [comment]
ah i think we need to clone git in CI (default is 1 and therefore change log id based on last commit)

**Comment by IgorMinar** [comment]
awesome! thanks

**Comment by IgorMinar** [comment]
@pi0 could you please also adjust the timestamp format as suggested above?

**Comment by pi0** [comment]
~> https://github.com/unjs/changelogen/issues/195
