### ISSUE TITLE
Is the unenv-nightly automation broken? The last release was a month ago

### ISSUE THREAD

**Issue by IgorMinar** [unjs/unenv#298]
### Environment

npm

### Reproduction

https://www.npmjs.com/package/unenv-nightly says that the last release was a month ago

https://github.com/unjs/unenv/pull/297 was merged last night and not released

### Describe the bug

automation seems broken :)

**Comment by pi0** [comment]
thanks for notice. for security, we use short lived publish tokens.

**Comment by vicb** [comment]
Thanks a lot @pi0 🙏
I'll update wrangler with the latest release

**Comment by IgorMinar** [comment]
thank you for resolving this promptly @pi0 !! 🧡
