### ISSUE TITLE
cloudflare: importing `node:http` wrongly import the unenv stream polyfill 

### ISSUE THREAD

**Issue by vicb** [unjs/unenv#353]
### Environment

https://github.com/unjs/unenv/commit/7a9f230e9c74783647ab598796e7da66be854f0f
Nodejs 22.11.0

### Reproduction

See https://github.com/unjs/unenv/pull/352/files#diff-2f5c73584260f31cbdff9f65cf07fd8f619f8b48ddda9d87e1e99d583ac0f87c

### Describe the bug

Without the PR, importing `node:http` also imports the unenv polyfill for stream because it is imported as a relative path.

Because the `Readable` polyfill does not implement the async iterator the test would throw `[unenv] Readable.asyncIterator is not implemented yet!`.

For cloudflare, the builtin stream implementation should be used instead.

### Additional context

See the comments in the [tentative PR](https://github.com/unjs/unenv/pull/352)

**Comment by vicb** [comment]
I am happy to help with this but I would need more info:

> This breaks the direct fetch / http call mechanism of nitro, h3, and unenv itself in the Node.js environment ([see this](https://srvx.unjs.io/guide/node#reverse-compatibility) for ref), the reason is that Node.js polyfills of node:http in unenv depend on other node: polyfills (such as node:net) which are compatible with each other changed in this PR.

I am not sure to understand the problem here.
Is there some code/tests I could run to figure out?

> I think we need to find a different way to solve worked situation (simplest way I would imagine is to add any missing API to polyfills) and if you can kindly please open an issue with reproduction first I would be happy to help but so sorry this is really not a possible solution.

We don't want to use the stream polyfill as it's builtin workerd.
What we want is that the http polyfill pulls in the builtin impl.
One solution could be to have a `$cloudflare-internal` containing the code from the PR - `internal` would be left unchanged and used outside of cloudflare.

> (BTW generally we migrated and should change all other imports to node:, I noticed few node:events were relative we should fix only http/net/streams are that currently are functional with each other)

I changed the relative imports to event in the tentative, are you saying I shouldn't have?
The rationale is the same: worked has a builtin implementation of events and we don't want to include the polyfill transitively.

**Comment by pi0** [comment]
> Is there some code/tests I could run to figure out?

[this example](https://srvx.unjs.io/guide/node#reverse-compatibility) is under production use for all nuxt, nitro, and h3 when users call `fetch('/url')` in their server handlers and emulates network request. It is an actual functionality not a stub in unenv which we cannot break (if we use `node:stream`, polyfill breaks, because actual node does not buffers). [here](https://github.com/unjs/unenv/tree/main/src/runtime/fetch), and [here](https://github.com/unjs/h3/blob/v1/src/adapters/plain.ts) are also other refs you can read if you like to know what is the usecase.

**Comment by vicb** [comment]
> I understand that workerd runtime also implements node:stream now but built-in unenv polyfills cannot depend on it as it breaks node:http functionality of unenv that nitro, h3 and more places depend on (not for cloudflare or node compat purpose).

So IIUC the only problem is with the import of stream in http.
Would it be possible to add a test to unenv to make sure we don't break things?

> Other imports such as node:events are fine and if there is any leftover place that depends on them we can refactor, PR welcome 👍🏼 (this won't break anything and unrelated)

I'll submit a PR.
I'll also add comments on the relative stream import in http so that we don't break things (hopefully we can add a test).

**Comment by vicb** [comment]
> as soon as we finish cloudflare preset externalization.

Is there a dependency here or is it only because this is the logical order of things.

I have worked on the testing story today, not there yet but hopefully early next week.

**Comment by pi0** [comment]
Having the external preset, we can also properly test the compatibility.

Do you know how/when https://github.com/opennextjs/opennextjs-cloudflare/issues/147 had been introduced? Does calling server actions from client components involve using `node:http` in Next.js?

**Comment by vicb** [comment]
> Do you know how/when https://github.com/opennextjs/opennextjs-cloudflare/issues/147 had been introduced?

No, I'll investigate next week to figure out the root cause.
I'll update the issue with my findings.
