### ISSUE TITLE
upgrade from v2 to bridge，unenv package load error 

### ISSUE THREAD

**Issue by 0xinhua** [unjs/unenv#44]
Hi，I need to ask for some help or advice，when I use `nuxi preview` to build for production file output，got the following  error: 

```
Rollup error: Could not load /project/node_modules/unenv/runtime/npm/node-fetch/lib/index.js.cjs: ENOENT: no such file or directory, open '/project/node_modules/unenv/runtime/npm/node-fetch/lib/index.js.cjs

Could not load /project/node_modules/unenv/runtime/npm/node-fetch/lib/index.js.cjs: ENOENT: no such file or directory, open '/project/node_modules/unenv/runtime/npm/node-fetch/lib/index.js.cjs'
```

Nuxt project info:                                                                            

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.16.0`
- Nuxt Version:     `2.16.0-27616340.013f051b`
- Package Manager:  `yarn@1.17.3`
- Builder:          `webpack`
- User Config:      `telemetry`, `hooks`, `mode`, `target`, `head`, `css`, `plugins`, `components`, `modules`, `build`, `srcDir`, `server`, `loading`, `render`, `publicRuntimeConfig`, `privateRuntimeConfig`, `proxy`, `serverMiddleware`, `router`, `serverHandlers`, `devServerHandlers`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/proxy@2.1.0`, `@nuxt/http@0.5.13`, `@nuxtjs/device@1.2.7`, `@nuxtjs/svg@0.1.12`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27636329.42ea75b`

**Comment by pi0** [comment]
Let's track it in bridge repo. It is hard to tell from here and is probably a bundling issue with nuxt2,bridge or nitro that adds extra `.js` to subpath.
