### ISSUE TITLE
Improve `npm:consola` mocks

### ISSUE THREAD

**Issue by pi0** [unjs/unenv#93]
unenv replaces consola back to console to save little bit from bundle. However with consola v3 the build is much smaller, we might use a "mini" export from it that keeps the interface.

**Comment by jimbo0378** [comment]
@pi0 Thanks for this change! Any idea when this is going to be released? Would really come in handy :D

**Comment by pi0** [comment]
Released. Sorry for delay.

**Comment by jimbo0378** [comment]
No problem, thanks for the release!
